### ISSUE TITLE
Cloudtube docker isn't working 

### ISSUE THREAD

**Issue by cinetube** [ABeltramo/cloudtube-docker#2]
Cloudtube docker isn't working. Please check the logs and suggest a solution. 

<img width="582" alt="Screenshot 2021-11-17 091247" src="https://user-images.githubusercontent.com/23441775/142128050-55c0dcf7-4f6b-43e1-a02c-2f76fd94dc8a.png">
<img width="420" alt="Screenshot 2021-11-17 091301" src="https://user-images.githubusercontent.com/23441775/142128052-68b87479-828b-4cc9-a6e1-778084292e55.png">
<img width="436" alt="Screenshot 2021-11-17 091319" src="https://user-images.githubusercontent.com/23441775/142128053-f87acd5a-f989-4921-8ab7-d1e3f3986b4e.png">

**Comment by JosephCW** [comment]
Did you use docker volumes to pass the config.js file and db folder through?

**Comment by cinetube** [comment]
> 
> 
> Did you use docker volumes to pass the config.js file and db folder through?

<img width="647" alt="Screenshot 2021-11-17 094432" src="https://user-images.githubusercontent.com/23441775/142130973-6ea03a1d-bd97-429c-bf84-237150fe064f.png">

I just ran these 2 dockers using these commands. I didn't do any changes at all.

**Comment by ABeltramo** [comment]
Please read the [examples](https://github.com/ABeltramo/cloudtube-docker/tree/main/examples).

**Comment by cinetube** [comment]
@ABeltramo Thanks it worked. I am facing some playback issues with 1080p videos. Where should I post about them?

**Comment by ABeltramo** [comment]
I'm glad it worked!

The best place to ask for help is probably the issue tracker at [cloudtube](https://todo.sr.ht/~cadence/tube) or you can ask directly on the [Matrix chatroom](https://matrix.to/#/#cloudtube:cadence.moe)
