### ISSUE TITLE
The double COPY in Dockerfile

### ISSUE THREAD

**Issue by colgrave34** [ABeltramo/cloudtube-docker#6]
Hello, I'm just a bit confused about the `COPY` in both Dockerfiles. 
In NewLeaf's Dockerfile: 
```
COPY ./requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

# If we already plan to copy the whole directory inside the container, shouldn't we just replace this line with the COPY ./requirements.txt ./requirements.txt? 
COPY . .
```
Same question in Cloudtube's Dockerfile. 
```
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN apt-get update -y && \
    apt-get install -y git python3 build-essential && \
    npm install && \
    apt-get remove -y --purge git python3 build-essential


COPY . .
```
For my testing, it works regardless. 
Does it affect anything? Or there's some other reason for this?

**Comment by ABeltramo** [comment]
Hello there! :wave: 
The reason for this split is fairly simple: it's to take full advantage of the Docker cache.  
Generally you change your code more than the dependencies, so, when you don't touch the `requirements.txt` or `package.json` the first steps will be cached and you'll only run the steps after `COPY . .`.  

I hope this clears your question, there are many resources available online if you want to go a bit deeper into this; the official docs are a pretty good starting point: https://docs.docker.com/build/cache/

**Comment by colgrave34** [comment]
Thanks so much, the explanation! 
I see you contribute to upstream too. https://git.sr.ht/~cadence/NewLeaf/tree/main/item/Dockerfile
The upstream Dockerfile has those lines. I'm wondering why we copy the requirement in to `/workdir` if we already in it. I don't see you doing the same thing in your repo. 
```
WORKDIR /workdir

COPY ./requirements.txt /workdir/requirements.txt
```

**Comment by ABeltramo** [comment]
Yeah, back in the days I've tried contributing upstream but since that was ignored I've setup this repo so that with the power of the free Github Actions I could automatically generate up-to-date Docker images.  
You are right, that extra `/workdir/` is not required in the original Dockerfile that you posted

**Comment by colgrave34** [comment]
Thanks a lot! I'll see if I can do something upstream.
